<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\**" />
    <Compile Remove="Views\Notification\**" />
    <Content Remove="Helpers\**" />
    <Content Remove="Views\Notification\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <EmbeddedResource Remove="Views\Notification\**" />
    <None Remove="Helpers\**" />
    <None Remove="Views\Notification\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\NotificationController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\js\FlatpickrScript.js" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Views\Shared\JavaScript.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.416.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.36" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.35">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Database\Database.csproj" />
    <ProjectReference Include="..\Helper\Helper.csproj" />
    <ProjectReference Include="..\Identity\Identity.csproj" />
  </ItemGroup>

</Project>
